services:
  chapter4_1:
    build: ./4_1/password_manager
    stdin_open: true
    tty: true
  chapter4_2:
    build: ./4_2/password_manager
    stdin_open: true
    tty: true
  chapter4_3:
    build: ./4_3/password_manager
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
  chapter4_prac:
    build: ./4_prac/password_manager
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
